name: Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  release:
    name: Release
    uses: hajle-silesia/.github/.github/workflows/shared-release.yaml@v2.5.0
    secrets:
      token: ${{ secrets.PUSH_TOKEN }}
